[package]
name = "typst-lua"
version = "0.1.0"
authors = ["geraldoluiz@puc-rio.br"]
edition = "2018"

# Add this line
[lib]
crate-type = ["cdylib"]

[dependencies]
#typst-genpdf = { git = "https://github.com/rousbound/typst-genpdf" }
typst-genpdf = { path = "../typst-genpdf" }
libc = "0.2"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
lua-sys = "0.2.0"

[build-dependencies]
cc = "1.0"
