[package]
name = "typst-lua"
version = "0.1.0"
authors = ["geraldoluiz@puc-rio.br"]
edition = "2018"

# Add this line
[lib]
crate-type = ["cdylib"]

[dependencies]
#typst-genpdf = { git = "https://github.com/rousbound/typst-genpdf" }
typst-compiler = { path = "../typst-compiler" }
libc = "0.2"
serde_json = "1.0"
lua-sys = "0.2.0"

[profile.release]
opt-level = 3

