name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Lua
      uses: leafo/gh-actions-lua@v8
    - name: Build
      run: cargo build --verbose
    - name: Run Rust tests
      run: cargo test --verbose
    - name: Run Lua tests
      run: |
        cd tests
        lua teste.lua
